name: Lint

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.3"

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Install dependencies (with dev)
        run: |
          poetry install --no-interaction --no-ansi --no-root --with dev

      - name: Black (check)
        run: |
          poetry run black --version
          poetry run black --check .

      - name: isort (check)
        run: |
          poetry run isort --version-number
          poetry run isort --check-only .

      - name: flake8 (lint)
        run: |
          poetry run flake8 --version
          poetry run flake8 .